In [1]:
import numpy as np

In [4]:
x=[1,2,3,4]
type(x)


list

In [6]:
y=np.array(x)
type(y)

numpy.ndarray

In [7]:
type(x),type(y)

(list, numpy.ndarray)

In [10]:
y/2

array([0.5, 1. , 1.5, 2. ])

In [19]:
x=[1,2,2.7+4j,"data"]
x

[1, 2, (2.7+4j), 'data']

In [20]:
y=np.array(x)
y

array(['1', '2', '(2.7+4j)', 'data'], dtype='<U64')

In [21]:
### random functions

In [44]:
data=np.random.randint(0,255,(3,3))

In [45]:
data

array([[193, 131, 176],
       [ 67, 185, 174],
       [131,  72, 153]], dtype=int32)

In [51]:
np.random.rand(3,3)

array([[0.5169353 , 0.49420447, 0.82992546],
       [0.24035496, 0.88208509, 0.84291269],
       [0.45564   , 0.07388526, 0.32339305]])

In [60]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [57]:
range(0,10)

range(0, 10)

In [67]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [70]:
np.arange(0,100,2)
np.linspace(0,10,4)
np.eye(3)
data.shape,data.size,data.ndim

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
data=np.random.randint(0,10,(3,3))
data

array([[2, 6, 0],
       [8, 7, 5],
       [9, 3, 5]], dtype=int32)

In [76]:
data.shape,data.size,data.ndim

((3, 3), 9, 2)

In [77]:
data=np.random.randint(0,10,(3,3))

In [78]:
data

array([[6, 9, 5],
       [7, 3, 1],
       [8, 5, 2]], dtype=int32)

In [79]:
data.T

array([[6, 7, 8],
       [9, 3, 5],
       [5, 1, 2]], dtype=int32)

In [80]:
data

array([[6, 9, 5],
       [7, 3, 1],
       [8, 5, 2]], dtype=int32)

In [105]:
import numpy as np
np.random.seed(121)
data=np.random.randint(0,100,(5,5))
data

array([[66, 85,  8, 95, 65],
       [52, 83, 96, 46, 34],
       [52, 60, 54,  3, 94],
       [52, 57, 75, 88, 39],
       [21, 41, 55, 83, 94]], dtype=int32)

In [113]:
data[2:4,-3:-1]

array([[54,  3],
       [75, 88]], dtype=int32)

In [109]:
data[4,0:2]

array([21, 41], dtype=int32)

In [108]:
data[0:4,4]

array([65, 34, 94, 39], dtype=int32)

In [107]:
data[0:2,0:2]

array([[66, 85],
       [52, 83]], dtype=int32)

In [106]:
data[0,0]

np.int32(66)

In [118]:
data

array([[66, 85,  8, 95, 65],
       [52, 83, 96, 46, 34],
       [52, 60, 54,  3, 94],
       [52, 57, 75, 88, 39],
       [21, 41, 55, 83, 94]], dtype=int32)

In [117]:
data[-3:-1,0:2]

array([[52, 60],
       [52, 57]], dtype=int32)

In [120]:
data=np.random.randint(0,10,(3,3))

In [121]:
data

array([[8, 3, 4],
       [3, 4, 2],
       [7, 7, 6]], dtype=int32)

In [123]:
data.sum(axis=1)

array([15,  9, 20])

In [124]:
data.sum(axis=0)

array([18, 14, 12])

In [125]:
data

array([[8, 3, 4],
       [3, 4, 2],
       [7, 7, 6]], dtype=int32)

In [127]:
data.min(axis=1)

array([3, 2, 6], dtype=int32)

In [128]:
data.min(axis=0)

array([3, 3, 2], dtype=int32)

In [129]:
data

array([[8, 3, 4],
       [3, 4, 2],
       [7, 7, 6]], dtype=int32)

In [130]:
data.max()

np.int32(8)

In [133]:
data

array([[8, 3, 4],
       [3, 4, 2],
       [7, 7, 6]], dtype=int32)

In [131]:
data.max(axis=1)

array([8, 4, 7], dtype=int32)

In [132]:
data.max(axis=0)

array([8, 7, 6], dtype=int32)

In [136]:
data.mean(axis=0)

array([6.        , 4.66666667, 4.        ])

In [137]:
data.mean(axis=1)

array([5.        , 3.        , 6.66666667])

In [139]:
data.mean()

np.float64(4.888888888888889)

In [140]:
data

array([[8, 3, 4],
       [3, 4, 2],
       [7, 7, 6]], dtype=int32)

In [146]:
data.argmin(axis=1)

array([1, 2, 2])

In [147]:
data

array([[8, 3, 4],
       [3, 4, 2],
       [7, 7, 6]], dtype=int32)

In [148]:
data.argmax(axis=0)

array([0, 2, 2])

In [ ]:
data.sum(axis=0),data.sum(axis=1),data.sum()
data.min(axis=0),data.min(axis=1),data.min()
data.max(axis=0),data.max(axis=1),data.max()
data.argmin(axis=0),data.argmin(axis=1),data.argmin()
data.argmax(axis=0),data.argmax(axis=1),data.argmax()
data.mean(axis=0),data.mean(axis=1),data.mean()

In [149]:
# NumPy Arithmetic Functions Example (Single Cell)

import numpy as np

# Creating two arrays
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Array A:", a)
print("Array B:", b)

# Addition
print("\nAddition (np.add):")
print(np.add(a, b))

# Subtraction
print("\nSubtraction (np.subtract):")
print(np.subtract(a, b))

# Multiplication
print("\nMultiplication (np.multiply):")
print(np.multiply(a, b))

# Division
print("\nDivision (np.divide):")
print(np.divide(a, b))

# Power
print("\nPower (np.power):")
print(np.power(a, b))

# Modulus
print("\nModulus (np.mod):")
print(np.mod(a, b))

# Floor Division
print("\nFloor Division (np.floor_divide):")
print(np.floor_divide(a, b))

# Absolute Difference
print("\nAbsolute Difference (np.abs):")
print(np.abs(a - b))

Array A: [10 20 30 40]
Array B: [1 2 3 4]

Addition (np.add):
[11 22 33 44]

Subtraction (np.subtract):
[ 9 18 27 36]

Multiplication (np.multiply):
[ 10  40  90 160]

Division (np.divide):
[10. 10. 10. 10.]

Power (np.power):
[     10     400   27000 2560000]

Modulus (np.mod):
[0 0 0 0]

Floor Division (np.floor_divide):
[10 10 10 10]

Absolute Difference (np.abs):
[ 9 18 27 36]


In [162]:
x=np.random.randint(0,10,(2,5))
y=np.random.randint(0,10,(2,10))

In [163]:
np.dot(x,y).shape

ValueError: shapes (2,5) and (2,10) not aligned: 5 (dim 1) != 2 (dim 0)

In [151]:
x

array([[4, 4],
       [9, 8]], dtype=int32)

In [152]:
y

array([[0, 7],
       [7, 1]], dtype=int32)

In [154]:
np.dot(x,y)

array([[28, 32],
       [56, 71]], dtype=int32)

In [164]:
data

array([[8, 3, 4],
       [3, 4, 2],
       [7, 7, 6]], dtype=int32)

In [165]:
from numpy.linalg import inv

In [166]:
inv(data)

array([[ 0.25 ,  0.25 , -0.25 ],
       [-0.1  ,  0.5  , -0.1  ],
       [-0.175, -0.875,  0.575]])

In [ ]:
#### 

In [167]:
#### NumPy Functions

In [168]:
a=np.array([4,9,16,25])
b=np.array([1,2,3,4])

In [173]:
np.e

2.718281828459045

In [174]:
print(np.sqrt(a))
print(np.square(b))
print(np.power(b,3))
print(np.exp(b))
print(np.log(a))
print(np.log2(a))
print(np.log10(a))

[2. 3. 4. 5.]
[ 1  4  9 16]
[ 1  8 27 64]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[1.38629436 2.19722458 2.77258872 3.21887582]
[2.         3.169925   4.         4.64385619]
[0.60205999 0.95424251 1.20411998 1.39794001]


In [175]:
np.log2(9)

np.float64(3.169925001442312)

In [176]:
2**3.169925001442312

8.999999999999998

In [177]:
a

array([ 4,  9, 16, 25])

In [180]:
x=a/2

In [181]:
x

array([ 2. ,  4.5,  8. , 12.5])

In [190]:
print(np.ceil(x))
print(np.floor(x))
print(np.round(x))
print(np.trunc(x))
print(np.sign([-10,20,0,10]))

[ 2.  5.  8. 13.]
[ 2.  4.  8. 12.]
[ 2.  4.  8. 12.]
[ 2.  4.  8. 12.]
[-1  1  0  1]


In [191]:
a

array([ 4,  9, 16, 25])

In [192]:
b

array([1, 2, 3, 4])

In [194]:
np.maximum(a,b*10)

array([10, 20, 30, 40])

In [2]:
import numpy as np

In [4]:
x=[1,2,3,4,5]

type(x)

list

In [5]:
y=np.array(x)

In [6]:
y

array([1, 2, 3, 4, 5])

In [8]:
type(x),type(y)

(list, numpy.ndarray)

In [9]:
y/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
x=[1,2,3,4+3j]

In [29]:
y=np.array(x)

In [30]:
y

array([  1.+0.j,   2.+0.j,   3.+0.j,   4.+3.j, -10.+0.j])

In [38]:
data=np.random.randint(0,100,(3,2))

In [39]:
data

array([[24, 31],
       [57, 66],
       [81, 19]], dtype=int32)

In [40]:
np.random.rand(3,3)

array([[0.02738348, 0.54579729, 0.90415953],
       [0.12915617, 0.06181081, 0.63551536],
       [0.26241034, 0.77882965, 0.45598427]])

In [42]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [43]:
range(1,1000)

range(1, 1000)

In [45]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [46]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
data = np.random.randint(1,10,(2,3))

In [52]:
data

array([[9, 9, 5],
       [2, 5, 3]], dtype=int32)

In [53]:
data.shape

(2, 3)

In [54]:
data.ndim

2

In [55]:
data.T

array([[9, 2],
       [9, 5],
       [5, 3]], dtype=int32)

In [56]:
import numpy as np
np.random.seed(121)
data=np.random.randint(0,100,(5,5))

data

array([[66, 85,  8, 95, 65],
       [52, 83, 96, 46, 34],
       [52, 60, 54,  3, 94],
       [52, 57, 75, 88, 39],
       [21, 41, 55, 83, 94]], dtype=int32)

In [57]:
data[2:4,-3:-1]

array([[54,  3],
       [75, 88]], dtype=int32)

In [59]:
data[3:,0:2]

array([[52, 57],
       [21, 41]], dtype=int32)

In [60]:
data[-2:,-2:]

array([[88, 39],
       [83, 94]], dtype=int32)

In [61]:
data=np.random.randint(0,10,(3,3))

In [62]:
data

array([[8, 3, 4],
       [3, 4, 2],
       [7, 7, 6]], dtype=int32)

In [78]:
data.min(axis=0)

array([3, 3, 2], dtype=int32)

In [79]:
data.mean(axis=0)

array([6.        , 4.66666667, 4.        ])

In [80]:
data

array([[8, 3, 4],
       [3, 4, 2],
       [7, 7, 6]], dtype=int32)

In [82]:
data.argmin(axis=1)

array([1, 2, 2])

In [84]:
data.argmax(axis=0)

array([0, 2, 2])

In [87]:
data.argmax(axis=1)

array([0, 1, 0])

In [88]:
import numpy as np

In [89]:
a= np.array([10,20,30,40])

b=np.array([2,4,6,8])

In [90]:
np.add(a,b)

array([12, 24, 36, 48])

In [95]:
np.subtract(a,b)

array([ 8, 16, 24, 32])

In [96]:
np.multiply(a,b)

array([ 20,  80, 180, 320])

In [97]:
np.divide(a,b)

array([5., 5., 5., 5.])

In [98]:
np.power(a,b)

array([          100,        160000,     729000000, 6553600000000])

In [99]:
np.mod(a,b)

array([0, 0, 0, 0])

In [100]:
np.floor_divide(a,b)

array([5, 5, 5, 5])

In [101]:
np.floor(a,b)

array([10, 20, 30, 40])

In [107]:
np.subtract(a,b)

array([0, 0, 0, 0])

In [108]:
a= np.array([10,20,30,40])

b=np.array([2,4,6,8])

In [110]:
abc=np.subtract(b,a)

In [111]:
np.abs(abc)

array([ 8, 16, 24, 32])

In [112]:
x=np.random.randint(0,10,(2,5))
y=np.random.randint(0,10,(2,10))

In [113]:
x

array([[4, 4, 9, 8, 0],
       [7, 7, 1, 3, 2]], dtype=int32)

In [114]:
y

array([[1, 4, 7, 0, 3, 7, 6, 1, 1, 9],
       [4, 3, 9, 2, 7, 5, 1, 6, 0, 8]], dtype=int32)